/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/server/wrangler.json --include-runtime=false` (hash: e6ee4d854e91fdb9472cb82ac35ba981)
interface __BaseEnv_Env {
	LOTTERY_DATA: R2Bucket;
	IMAGES: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
